ELEVATOR_IMAGE = 'resources/elv-small.png'
BRICK_TEXTURE = 'resources/brick-texture.png'
BOX_LEN = 800
BOX_HEIGHT = 600

FLOOR_HEIGHT = 58
INITIAL_FLOOR_Y = 550
BUTTON_RADIUS = 20
BUILDING_X = 10

FLOOR_TRANSIT_TIME = 0.2
PIXELS_PER_SECOND = 116

SPEED_STOP = 0
SPEED_NORMAL = 2
SPEED_FINAL = 1
DELAY_AT_ARRIVAL = 2
LAST_TIME = 0

